### PR TITLE
MNT: Cleanup CartoPy example

### PR DESCRIPTION
**Pull request by zbruick**
- Remove use of `ax.coastlines`
 - Simplify the wind barb example a little

Example could maybe be simplified more. Most confusing part to participants is probably the synthetic data creation, but not sure how to get around that.

### CODE REVIEW

**Comment by zbruick** [comment]
Closes #446.

**Comment by dopplershift** [comment]
I can't remember, do we have to use a grid for CartoPy's `barbs()` wrapper to do the reprojection? Otherwise, could just create 2-3 points of wind observations. I also wonder regardless if the `contour` plot is needlessly muddying the waters.

**Comment by zbruick** [comment]
I'll look to see if we need the grid. And I'm not a huge fan of the contour lines overall, as we demo it in other notebooks. I'll remove that.

**Comment by dopplershift** [comment]
Merging over Travis since it's going to fail due to Siphon right now.

**Pull request merged**
