### PR TITLE
Add example of WTx and OK mesonet station plotting

### PR DESCRIPTION
**Pull request by zbruick**
For initial use at the TTU workshop. Happy to take suggestions on improving it. 

cc: @deeplycloudy and @dopplershift

### CODE REVIEW

**Comment by deeplycloudy** [comment]
Some other ideas / suggested activities:
- [ ] WT data are in LST not UTC. Solar rad plot confirms this.
- [ ] convert time column to datetime64 and then to UTC
- [ ] show time math - calculate time deltas to look at observation cadence
- [ ] instead of one time, look at result of merge for a whole hour of samples
- [ ] plot a time series and the hourly mean of that time series for a station

```
import numpy as np

# Select daylight hours
tx_time_sub = tx_data[(tx_data['Time'] >= 600) & (tx_data['Time'] <= 2000)]

tx_merge = pd.merge(tx_time_sub, tx_stations, left_on='Station_ID', right_on='Logger ID')


# Create sub-tables for each station
tx_grp = tx_merge.groupby('ID')
print(tx_grp.groups.keys())

# Get data from station DIMM
station_data = tx_grp.get_group('DIMM')

# Create hourly averaged data
time_bins = pd.cut(station_data['Time'], np.arange(600, 2100, 100))
# xarray has groupby_bins, but pandas has cut
station_hourly = station_data.groupby(time_bins)
station_hourly_mean = station_hourly.mean()
print(station_data.columns)
for t, values in station_hourly:
    print(t, values['Time'])
# station_data

print(station_hourly_mean['Time'])
```
```
import matplotlib.pyplot as plt
fig = plt.figure()
ax= fig.add_subplot(111)
station_data.plot('Time', 'solar_radiation', ax=ax)
station_hourly_mean.plot('Time', 'solar_radiation', ax=ax)
```
The 5-min time series plot above looks oddly not-smooth, which is probably because of the jump from minute 55 to minute 0 in the next hour. (e.g., 755, 800). This is why we need to convert to a datetime64 object, which is continuous nanoseconds.

Bonus evolution of the code:
- [ ] Convert to xarray, add unit metadata, etc.

**Comment by zbruick** [comment]
Added the time series plotting from @deeplycloudy. Could definitely use some help on the time handling aspect here, as it is definitely not easy to work with as is. I have a commented out line that I tried, but doesn't work yet for me. As far as the other ideas from @deeplycloudy, I'm not sure how much more time we should be adding to this notebook. If others have a better sense of that, feel free to provide input.

**Comment by zbruick** [comment]
Oh upstream dependencies...xarray v0.14 came out and broke our satellite plots because we're importing stuff from xarray.core that went away. I'll try updating those notebooks to finally get a clean Travis build.

**Comment by zbruick** [comment]
I think this ready for a new review...no failures on the changes introduced here.

**Comment by dopplershift** [comment]
Power-cycled to try to get appveyor to show up (the config had been broken for 7 months since we renamed the repo). This *should* pass now that I put up patched conda packages.

**Pull request merged**
