### PR TITLE
MNT: Updated timings in notebooks, unpinned pint

### LINKED ISSUE #417: Fix up timings
Here are the notes I took on timing from the Albany workshop:

* Jupyter 1 hour
* Numpy 1 hour
* Pandas 1:15
* Xarray 45
* Matplotlib 30 — way too fast for all
* MetPy 45
* Siphon 20
* Pythonic (intro only) 1:20
* Cartopy 25 lecture, 15 exercise
* Skewt 40 for about half
* Satellite 1 hour
* Model 40
* QG 1:15

We need to put more accurate timings in the headers for the notebooks and we should make sure our future agendas better reflect this.

### PR DESCRIPTION
**Pull request by zbruick**
Updated timings in notebooks as reflected by #417 to match #427. Also unpinned pint since MetPy 0.10.2 fixes the issues we had it that was causing it to be pinned.

Closes #417.

### CODE REVIEW

**Comment by dopplershift** [comment]
Looks like SkewT is having problems plotting the 0 degree isotherm. Can you investigate and figure out how best to fix?

**Comment by zbruick** [comment]
So this is a new problem with pint 0.9 it appears (hooray...). I'll look into it more but I would not think this would be desired functionality in pint. In the meantime, we can re-pin pint to 0.8.1 or drop the units from the plotting line here.

**Comment by dopplershift** [comment]
I think `ax.axvline([0] * units.degC)` would also work. A little ugly, but keeps us from dropping or pinning. The problem is that `np.iterable(1 * units.meter)` returns `True` while `np.iterable(1)` returns `False`. A bug in `pint` I think.

**Comment by zbruick** [comment]
This was already open back from February but hasn't been addressed. I added our issue to this thread: https://github.com/hgrecco/pint/issues/760

**Comment by jthielen** [comment]
That looks like the same upstream issue noted in https://github.com/Unidata/MetPy/pull/1087 (ref https://github.com/hgrecco/pint/issues/751).

**Comment by zbruick** [comment]
Used @dopplershift's patch for now until pint deals with that issue.

**Comment by dopplershift** [comment]
Ugh, the other Pandas PR I merged has a minor conflict with this.

**Pull request merged**
